# Usa la imagen de Node (última versión)
FROM node

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia el package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Expone el puerto 5173
EXPOSE 5173

# Ejecuta el comando npm run dev para el entorno de desarrollo
CMD ["npm", "run", "dev"]
